// apps/taro-app/src/components/map/textarea.tsx
import { View, Text, Slider, Textarea } from '@tarojs/components'

export default () => {
  return (
    <View>
      <View className='subtitle'>颜色类型</View>
      <View className='grid grid-cols-1 gap-2'>
        <Textarea className='textarea textarea-bordered' placeholder='bordered placeholder'></Textarea>
        <Textarea className='textarea textarea-primary' placeholder='primary placeholder'></Textarea>
        <Textarea className='textarea textarea-success' placeholder='success placeholder'></Textarea>
        <Textarea className='textarea textarea-warning' placeholder='warning placeholder'></Textarea>
        <Textarea className='textarea textarea-error' placeholder='error placeholder'></Textarea>
        <Textarea className='textarea textarea-neutral' placeholder='neutral placeholder'></Textarea>
      </View>
      <View className='subtitle'>禁用</View>
      <View className='grid grid-cols-1 gap-2'>
        <Textarea className='textarea textarea-bordered textarea-disabled' placeholder='placeholder'></Textarea>
      </View>
      <View className='subtitle'>尺寸</View>
      <View className='grid grid-cols-1 gap-2'>
        <Textarea className='textarea textarea-bordered textarea-xs' placeholder='placeholder'></Textarea>
        <Textarea className='textarea textarea-bordered textarea-sm' placeholder='placeholder'></Textarea>
        <Textarea className='textarea textarea-bordered textarea-md' placeholder='placeholder'></Textarea>
        <Textarea className='textarea textarea-bordered textarea-lg' placeholder='placeholder'></Textarea>
      </View>
    </View>
  )
}

// examples/unocss-sample-app/src/components/textarea.vue
<script setup lang="ts"></script>

<template>
  <textarea class="textarea" placeholder="Bio"></textarea>

  <textarea class="textarea textarea-bordered" placeholder="Bio"></textarea>

  <textarea class="textarea textarea-ghost" placeholder="Bio"></textarea>

  <label class="form-control">
    <div class="label">
      <span class="label-text">Your bio</span>
      <span class="label-text-alt">Alt label</span>
    </div>
    <textarea class="textarea h-24 textarea-bordered" placeholder="Bio"></textarea>
    <div class="label">
      <span class="label-text-alt">Your bio</span>
      <span class="label-text-alt">Alt label</span>
    </div>
  </label>

  <textarea class="textarea textarea-primary" placeholder="Bio"></textarea>

  <textarea class="textarea textarea-secondary" placeholder="Bio"></textarea>

  <textarea class="textarea textarea-accent" placeholder="Bio"></textarea>

  <textarea class="textarea textarea-info" placeholder="Bio"></textarea>

  <textarea class="textarea textarea-success" placeholder="Bio"></textarea>

  <textarea class="textarea textarea-warning" placeholder="Bio"></textarea>

  <textarea class="textarea textarea-error" placeholder="Bio"></textarea>

  <div class="flex flex-col gap-4 w-full items-center">
    <textarea
      placeholder="Bio"
      class="textarea textarea-bordered textarea-xs w-full max-w-xs"
    ></textarea>
    <textarea
      placeholder="Bio"
      class="textarea textarea-bordered textarea-sm w-full max-w-xs"
    ></textarea>
    <textarea
      placeholder="Bio"
      class="textarea textarea-bordered textarea-md w-full max-w-xs"
    ></textarea>
    <textarea
      placeholder="Bio"
      class="textarea textarea-bordered textarea-lg w-full max-w-xs"
    ></textarea>
  </div>

  <textarea class="textarea" placeholder="Bio" disabled=""></textarea>
</template>
