// apps/taro-app/src/pages/index/index.tsx
import { View, Text, Button, ViewProps } from '@tarojs/components'
// import { useLoad } from '@tarojs/taro'
// import React, { useState, Fc } from 'react'
import './index.scss'
import { useEffect } from 'react'
import { io } from 'socket.io-client'

export default function Index() {
  // useEffect(() => {
  //   // const ws = new WebSocket('http://localhost:3000')

  //   const socket = io('http://localhost:3000/events', {
  //     reconnectionDelayMax: 10000,
  //     auth: {
  //       token: '123'
  //     },
  //     query: {
  //       'my-key': 'my-value'
  //     },
  //     transports: ['polling', 'websocket']
  //   })
  //   socket.on('connect', function () {
  //     console.log('Connected')

  //     socket.emit('events', { test: 'test' })
  //     socket.emit('identity', 0, (response) => console.log('Identity:', response))
  //   })
  //   socket.on('events', function (data) {
  //     console.log('event', data)
  //   })
  //   socket.on('exception', function (data) {
  //     console.log('event', data)
  //   })
  //   socket.on('disconnect', function () {
  //     console.log('Disconnected')
  //   })

  //   socket.on('connect_error', (error) => {
  //     console.error(error)
  //   })
  // })
  return <View className='bg-[rgb(37,37,37)] card'>12345</View>
}

// apps/uni-app-vue3/src/pages/index/index.vue
<script setup lang="ts">
import BaseLayout from '@/components/BaseLayout.vue'
import { io } from 'socket.io-client'

onLoad(() => {
  const socket = io('http://localhost:3000/events', {
    reconnectionDelayMax: 10000,
    auth: {
      token: '123',
    },
    query: {
      'my-key': 'my-value',
    },
    transports: ['polling', 'websocket'],
  })
  socket.on('connect', () => {
    console.log('Connected')

    socket.emit('events', { test: 'test' })
    socket.emit('identity', 0, response => console.log('Identity:', response))
  })
  socket.on('events', (data) => {
    console.log('event', data)
  })
  socket.on('exception', (data) => {
    console.log('event', data)
  })
  socket.on('disconnect', () => {
    console.log('Disconnected')
  })

  socket.on('connect_error', (error) => {
    console.error(error)
  })
})
</script>

<template>
  <BaseLayout>
    <view
      class="text-[#5cab3d] deep:text-red-300 dark:text-red-600 fantasy:text-red-900"
    >
      111
    </view>
  </BaseLayout>
</template>

<style lang="scss" scoped></style>
