// examples/unocss-sample-app/src/components/diff.vue
<script setup lang="ts"></script>

<template>
  <div>
    <div class="diff rounded-btn aspect-[16/9]">
      <div class="diff-item-1"><img alt="IceStack" src="/pig.jpg" /></div>
      <div class="diff-item-2"><img alt="IceStack" src="/pig.jpg" /></div>
      <div class="diff-resizer"></div>
    </div>

    <div class="diff rounded-btn aspect-[16/9]">
      <div class="diff-item-1">
        <div
          class="bg-primary text-primary-content text-4xl lg:text-9xl font-black grid place-content-center"
        >
          IceStack
        </div>
      </div>
      <div class="diff-item-2">
        <div class="bg-base-200 text-4xl lg:text-9xl font-black grid place-content-center">
          IceStack
        </div>
      </div>
      <div class="diff-resizer"></div>
    </div>
  </div>
</template>

// apps/taro-app/src/components/map/diff.tsx
import { View, Text, Button, ViewProps } from '@tarojs/components'

export default () => {
  return (
    <View>
      <View className='subtitle'>默认使用</View>
      <View>
        <View className='diff aspect-[16/9]'>
          <View className='diff-item-1'>
            <View className='font-black grid place-content-center'>XXXX</View>
          </View>
          <View className='diff-item-2'>
            <View className='font-black grid place-content-center'>XXXX</View>
          </View>
          <View className='diff-resizer'></View>
        </View>
      </View>
    </View>
  )
}
