// examples/unocss-sample-app/src/components/mask.vue
<script setup lang="ts"></script>

<template>
  <div>
    <img alt="Squircle CSS mask" class="mask mask-squircle w-40 h-40" src="/pig.jpg">

    <img alt="Heart CSS mask" class="mask mask-heart w-40 h-40" src="/pig.jpg">

    <img alt="Hexagon CSS mask" class="mask mask-hexagon w-40 h-40" src="/pig.jpg">

    <img alt="Hexagon-2 CSS mask" class="mask mask-hexagon-2 w-40 h-40" src="/pig.jpg">

    <img alt="Decagon CSS mask" class="mask mask-decagon w-40 h-40" src="/pig.jpg">

    <img alt="Pentagon CSS mask" class="mask mask-pentagon w-40 h-40" src="/pig.jpg">

    <img alt="Diamond CSS mask" class="mask mask-diamond w-40 h-40" src="/pig.jpg">

    <img alt="Square CSS mask" class="mask mask-square w-40 h-40" src="/pig.jpg">

    <img alt="Circle CSS mask" class="mask mask-circle w-40 h-40" src="/pig.jpg">

    <img alt="Parallelogram CSS mask" class="mask mask-parallelogram w-40 h-40" src="/pig.jpg">

    <img
      alt="Parallelogram-2 CSS mask"
      class="mask mask-parallelogram-2 w-40 h-40"
      src="/pig.jpg"
    >

    <img
      alt="Parallelogram-3 CSS mask"
      class="mask mask-parallelogram-3 w-40 h-40"
      src="/pig.jpg"
    >

    <img
      alt="Parallelogram-4 CSS mask"
      class="mask mask-parallelogram-4 w-40 h-40"
      src="/pig.jpg"
    >

    <img alt="Star CSS mask" class="mask mask-star w-40 h-40" src="/pig.jpg">

    <img alt="Star-2 CSS mask" class="mask mask-star-2 w-40 h-40" src="/pig.jpg">

    <img alt="Triangle CSS mask" class="mask mask-triangle w-40 h-40" src="/pig.jpg">

    <img alt="Triangle-2 CSS mask" class="mask mask-triangle-2 w-40 h-40" src="/pig.jpg">

    <img alt="Triangle-3 CSS mask" class="mask mask-triangle-3 w-40 h-40" src="/pig.jpg">

    <img alt="Triangle-4 CSS mask" class="mask mask-triangle-4 w-40 h-40" src="/pig.jpg">
  </div>
</template>

// apps/taro-app/src/components/map/mask.tsx
import CodeRender from '@/components/CodeRender'
import { Image, View } from '@tarojs/components'
import { cx } from 'class-variance-authority'
import panda from '../../assets/panda.jpg'

const list = [
  'mask-squircle',
  'mask-decagon',
  'mask-diamond',
  'mask-heart',
  'mask-hexagon',
  'mask-hexagon-2',
  'mask-circle',
  'mask-parallelogram',
  'mask-parallelogram-2',
  'mask-parallelogram-3',
  'mask-parallelogram-4',
  'mask-pentagon',
  'mask-square',
  'mask-star',
  'mask-star-2',
  'mask-triangle',
  'mask-triangle-2',
  'mask-triangle-3',
  'mask-triangle-4',
]
export default () => {
  return (
    <View>
      <View className="subtitle">遮罩类型</View>
      <CodeRender className="grid grid-cols-3 gap-2">
        {list.map((x) => {
          return <Image key={x} className={cx('w-full mask', x)} mode="widthFix" src={panda}></Image>
        })}
      </CodeRender>
    </View>
  )
}
